// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using vuebnb.Models;

namespace vuebnb.Migrations
{
    [DbContext(typeof(ListingContext))]
    partial class ListingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vuebnb.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<string>("Address");

                    b.Property<bool>("AmenityBreakfast");

                    b.Property<bool>("AmenityKitchen");

                    b.Property<bool>("AmenityLaptop");

                    b.Property<bool>("AmenityPetsAllowed");

                    b.Property<bool>("AmenityTv");

                    b.Property<bool>("AmenityWifi");

                    b.Property<string>("PriceExtraPeople");

                    b.Property<string>("PriceMonthlyDiscount");

                    b.Property<string>("PricePerNight");

                    b.Property<string>("PriceWeeklyDiscount");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
